name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: go to backend
        run: cd /src/backend
      - name: Install dependencies
        run: npm install
      - name: Build npm
        run: npm run build --if-present
      - name: Start tests
        run: npm test
